apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-v1"
  labels:
    version: v1
spec:
  replicas: {{ .Values.replicaCount.v1 }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
      version: v1
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
        version: v1
    spec:
      containers:
        - name: "{{ .Values.app.name }}-v1"
          image: "{{ .Values.image.repository }}:{{ .Values.image.v1Tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.app.name }}-v2"
  labels:
    version: v2
spec:
  replicas: {{ .Values.replicaCount.v2 }}
  selector:
    matchLabels:
      app: "{{ .Values.app.name }}"
      version: v2
  template:
    metadata:
      labels:
        app: "{{ .Values.app.name }}"
        version: v2
    spec:
      containers:
        - name: "{{ .Values.app.name }}-v2"
          image: "{{ .Values.image.repository }}:{{ .Values.image.v2Tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}